### ISSUE TITLE
Check, Forgot your Password?

### ISSUE THREAD

**Issue by samuel-vergara-leon** [Azordev/art-marketplace#12]
### EXPLANATION 

It is located in the login section next to the email input and with tertiary color letters with code #11698E, its function is to recover the password through email, such email is the same that the user previously used to get his account.

### SCREENSHOTS
<img width="184" alt="image" src="https://user-images.githubusercontent.com/97471255/153050314-ecae4257-161c-47b5-84b4-d82da348dfa6.png">

### Step by step reproduction of the issue

- Open the app https://art-marketplace.pages.dev/
- Go to login page in https://art-marketplace.pages.dev/login
- inspect for the text "¿Has olvidado tu contraseña?"
- Verify that pressing it have old design (red accents)

### CHECKLIST
- [ ] Helps people who once had an account on this website to recover their user.
- [ ] The password recovery data is subject to the email with which the user had initially registered.
- [ ] There is a list of steps to follow to recover the password

### REFERENCES
https://www.figma.com/file/zzEwuPfGTiZh4EA11MyZ5c/Sencico?node-id=65%3A2

**Comment by Katsu08** [comment]
Please change checklist, I would say add the new changes instead of describe the "Forget your Password" function. I meant:

- The "¿Has olvidado tu contraseña?" text now is blue #XXXXXX
- The font size is now XXpx
- When clicks on "¿Has olvidado tu contraseña?" a box appear showing the support contact
