### ISSUE TITLE
Delete Unnecessary Sections On The Web Page

### ISSUE THREAD

**Issue by samuel-vergara-leon** [Azordev/art-marketplace#38]
### Explanation
The images that are presented correspond to the footer and the registration section. The footer is located at the bottom of each section and the registration section is located at the end of it. Each part named above (footer and registration section) presents icons and images of Peru and they are in right and left part of the Azordef symbol. These images do not match the Sencico design and therefore should not be there.

The section of our collaborators is located at the bottom of the previous Sencico design, unlike the current design that does not have it.

### SCREENSHOTS

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/97471255/155141841-f9c2e646-6548-4689-b662-5517bd913f3c.png">

<img width="1400" alt="image" src="https://user-images.githubusercontent.com/97471255/155144699-09378b21-f94f-4bec-b847-1e31f101c8c9.png">

<img width="1346" alt="image" src="https://user-images.githubusercontent.com/97471255/155143765-443c5259-f651-40fd-a58b-6e9d74062d34.png">

### CHECKLIST

- [ ] Remove "LogosFooter.jsx" component from views where it is present.
- [ ] Remove "PartnersSlider.jsx" component from views where it is present.
- [ ] Delete the "LogosFooter.jsx" and "PartnersSlider.jsx" files from the project.
- [ ] Add "Footer.jsx" component in Login and Register.

### REFERENCES
https://www.figma.com/file/zzEwuPfGTiZh4EA11MyZ5c/Sencico?node-id=65%3A2
https://art-marketplace.pages.dev/register
https://art-marketplace.pages.dev/login

**Comment by Katsu08** [comment]
The images to should deleted are all. I meant: 

Please delete this section complete
![imagen](https://user-images.githubusercontent.com/66505715/155011572-b288c76a-1693-467c-84d3-fe1bdff2c328.png)
Please delete too this section complete
![imagen](https://user-images.githubusercontent.com/66505715/155011622-78972d11-d56f-434f-954e-4a720d7d71f5.png)

If they're components please delete the component file since this doesn't was used.

**Comment by Allislove** [comment]
Done in PR #50
