### ISSUE TITLE
Improvements to the ArtworkItem component

### ISSUE THREAD

**Issue by e-azocar** [Azordev/art-marketplace#56]
### Explanation:

Improvements to the ArtworkItem component.

### Screenshots
 If applicable, add screenshots to help explain.

### Checklist
 Describe the key points to complete the task. This points will help in the pull request test.

 This issue can be closed when the following tasks are completed:
 
 - [ ] Change `alt` of the images to the title of the work or something that represents the component.
 - [ ] Remove the default image `Desing1`, since all elements have an image.
 - [ ] Change "Product Name" to other text when you can't find it.

**Comment by Allislove** [comment]
@e-azocar Why we weill delete the default image?
I think if the API, fails, the app can use this!! not ?

**Comment by Allislove** [comment]
Done in PR #65 review if isn't necessary to remove the Design1 image, i think isn't necessary!

**Comment by heliomar-pena** [comment]
> @e-azocar Why we weill delete the default image? I think if the API, fails, the app can use this!! not ?

Hello! I think an art gallery doesn't should show a default image because this can be confused with the original artwork haha.

The currently default image is a chair, I think would be better to add a default image that says some like "Image not found", but I think that adding the original artwork name in the "alt" of the image can be a good solution

![imagen](https://user-images.githubusercontent.com/66505715/157477974-06901e7e-e92f-4927-8e0c-333900cc61eb.png)

**Comment by Allislove** [comment]
So just added a new image and new alt ? Can you give me what img ?? And what alt if is possible.

**Comment by heliomar-pena** [comment]
For now just add "alt" and remove the image, since I don't find a "Not found image" image hahaha. 

The alt can be the title of the artwork, for example

`<img src="claveland.com/example/monalisa" alt="Monalisa" />`

I meant, for example:

`<img src="${artwork.url}" alt="${artwork.title}">`
